WITH TC(SRC, DST, LVL, "PATH") AS (
  SELECT SRC, DST, 0,
         CAST('-' + CAST(SRC AS VARCHAR(10)) + '-' + CAST(DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE
  WHERE SRC BETWEEN 3858241 AND 3879754
  UNION ALL
  SELECT EDGE.SRC, EDGE.DST, TC.LVL+1,
         CAST(TC."PATH" + CAST(EDGE.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM TC, EDGE
  WHERE TC.DST=EDGE.SRC
    AND "PATH" NOT LIKE '%-' + CAST(EDGE.DST AS VARCHAR(10)) + '-%'
)
SELECT SRC, DST, LVL, "PATH"
FROM TC
;
