WITH SG (SG1, SG2, LVL, "PATH") AS (
  SELECT E1.DST, E2.DST, 0,
         CAST('-' + CAST(E1.SRC AS VARCHAR(10)) + '-' + CAST(E1.DST AS VARCHAR(10)) + '-' + CAST(E2.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE E1, EDGE E2
  WHERE E1.SRC=E2.SRC
    AND E1.DST <> E2.DST
    AND E1.SRC BETWEEN 3858241 AND 3879754
  UNION ALL
  SELECT E1.DST, E2.DST, LVL+1,
         CAST("PATH" + CAST(E1.DST AS VARCHAR(10)) + '-' + CAST(E2.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE E1, SG, EDGE E2
  WHERE E1.SRC=SG.SG1
    AND SG.SG2=E2.SRC
    AND "PATH" NOT LIKE '%-' + CAST(E1.DST AS VARCHAR(10)) + '-%'
    AND "PATH" NOT LIKE '%-' + CAST(E2.DST AS VARCHAR(10)) + '-%'
)
SELECT SG1, SG2, LVL, "PATH"
FROM SG
;
