WITH REACH(DST, LVL, "PATH") AS (
  SELECT DST, 0,
         CAST('-' + CAST(SRC AS VARCHAR(10)) + '-' + CAST(DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE
  WHERE SRC BETWEEN 3858241 AND 3879754
  UNION ALL
  SELECT EDGE.DST, REACH.LVL+1,
         CAST(REACH."PATH" + CAST(EDGE.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM REACH, EDGE
  WHERE REACH.DST=EDGE.SRC
    AND "PATH" NOT LIKE '%-' + CAST(EDGE.DST AS VARCHAR(10)) + '-%'
)
SELECT DST, LVL, "PATH"
FROM REACH
;
