WITH SSSP(SRC, DST, WEIGHT, LVL, "PATH") AS (
  SELECT SRC, DST, WEIGHT, 0,
         CAST('-' + CAST(SRC AS VARCHAR(10)) + '-' + CAST(DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE
  WHERE SRC BETWEEN 3858241 AND 3879754
  UNION ALL
  SELECT SSSP.SRC, EDGE.DST, SSSP.WEIGHT+EDGE.WEIGHT, SSSP.LVL+1,
         CAST(SSSP."PATH" + CAST(EDGE.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM SSSP, EDGE
  WHERE SSSP.DST=EDGE.SRC
    AND "PATH" NOT LIKE '%-' + CAST(EDGE.DST AS VARCHAR(10)) + '-%'
),
MIN_WEIGHT(DST, WEIGHT) AS (
  SELECT DST, MIN(WEIGHT)  
  FROM SSSP 
  GROUP BY DST
) 
SELECT S.SRC, S.DST, S.WEIGHT AS MIN_WEIGHT, S.LVL, S."PATH"
FROM SSSP S, MIN_WEIGHT M  
WHERE S.DST=M.DST 
  AND S.WEIGHT=M.WEIGHT 
;
