WITH CC(SRC, CMPID, LVL, "PATH") AS (
  SELECT SRC, SRC, 0,
         CAST('-' + CAST(SRC AS VARCHAR(10)) + '-' + CAST(SRC AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM EDGE
  WHERE SRC BETWEEN 3858241 AND 3879754
  UNION ALL
  SELECT E.DST, C.CMPID, C.LVL+1,
         CAST(C."PATH" + CAST(E.DST AS VARCHAR(10)) + '-' AS VARCHAR(1024)) 
  FROM CC C, EDGE E
  WHERE C.SRC=E.SRC
    AND "PATH" NOT LIKE '%-' + CAST(E.DST AS VARCHAR(10)) + '-%'
),
MIN_CMPID(SRC, CMPID) AS (
  SELECT SRC, MIN(CMPID) 
  FROM CC 
  GROUP BY SRC
) 
SELECT C.SRC, C.CMPID 
FROM CC C, MIN_CMPID M 
WHERE C.SRC=M.SRC 
  AND C.CMPID=M.CMPID 
;
